version: '3'

tasks:
  lint:
    cmds:
      - pdm install -G lint
      - pdm run ruff check --fix
  scan:
    cmds:
      - pdm install -G scan
      - pdm run bandit -c pyproject.toml -r src/
  setup:
    cmds:
      - pdm python install
      - pdm install --dev
      - pdm install
  test:
    cmds:
      - pdm install -G test
      - pdm run tox -p all

